# Generated by Django 4.2.13 on 2024-07-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storegrupozero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='techniques/'),
        ),
    ]
